apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
        app: my-app

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - image: nginx:1.7.9
        name: my-nginx
        volumeMounts:
          - name: my-host-path
            mountPath: /public_html
          - name: nginx-config-volume
            mountPath: /etc/nginx
          
      - image: php:7.2-fpm
        name: app-php
        volumeMounts:
          - name: my-host-path
            mountPath: /public_html

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: my-host-path
        hostPath:
          path: /Users/shoeb240/easy-kubernetes-nginx-php/public_html
          type: Directory